### PR TITLE
Map touch ups

### LINKED ISSUE #78: Client/Map-diplay: Set the bounds of the map to NYC

### PR DESCRIPTION
**Pull request by Tiffany-Zhu5303**
## Description
Updates on the map display.

## What's in this change?

- [X]  map bounded to NYC area
- [X]  updated icons to be colored by categories
- [X]  updated marker sizing to scale to map zoom in

## Testing changes
N/A

### CODE REVIEW

**Review by keunsublee — COMMENTED** [review]
The new markers are nice! I deployed the branch on render

some notes:
zoom in/out on map doesnt work when a filter is selected nor on search
also a little slower to zoom in/out when all markers are loaded
out of bounds works on search/filter but not on first load/all filter
(this might be bc of how search and filter is written)

**Comment by Tiffany-Zhu5303** [comment]
`DynamicMarker` was implemented to handle the sizing of the markers when zooming in and out. 
There appears to be some issue where it's causing the `MapCenterUpdater`'s `useEffect` to rerender and reposition the user's view away from where they more to be.

**Review by ghost — APPROVED** [review]
Good job!

**Review by perlaescano — APPROVED** [review]
Looks good! Great work!

**Pull request merged**
